# Generated by Django 6.1 on 2026-08-27 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_order_country_remove_order_order_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='order_status',
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default='Somalia', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='mobile_money_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product'),
        ),
        migrations.AlterField(
            model_name='paymentsetting',
            name='edahab_number',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='E-Dahab Business Number'),
        ),
        migrations.AlterField(
            model_name='paymentsetting',
            name='sahal_number',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Sahal Business Number'),
        ),
        migrations.AlterField(
            model_name='paymentsetting',
            name='zaad_number',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Zaad Business Number'),
        ),
    ]
