# Generated by Django 6.1 on 2026-08-27 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_status_order_order_status_order_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mobile_money_provider',
            field=models.CharField(blank=True, choices=[('zaad', 'Zaad'), ('edahab', 'E-Dahab'), ('sahal', 'Sahal')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card Payment'), ('mobile_money', 'Mobile Money')], default='mobile_money', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentsetting',
            name='edahab_number',
            field=models.CharField(blank=True, default='', help_text='Numberka ganacsiga ee lacagta E-Dahab lagu soo dirayo.', max_length=30, verbose_name='E-Dahab Business Number'),
        ),
        migrations.AlterField(
            model_name='paymentsetting',
            name='sahal_number',
            field=models.CharField(blank=True, default='', help_text='Numberka ganacsiga ee lacagta Sahal lagu soo dirayo.', max_length=30, verbose_name='Sahal Business Number'),
        ),
        migrations.AlterField(
            model_name='paymentsetting',
            name='zaad_number',
            field=models.CharField(blank=True, default='', help_text='Numberka ganacsiga ee lacagta Zaad lagu soo dirayo.', max_length=30, verbose_name='Zaad Business Number'),
        ),
    ]
