# Generated by Django 6.1 on 2026-08-29 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at']},
        ),
    ]
