# Generated by Django 6.0.4 on 2026-08-31 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_contactmessage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='My Store', max_length=100)),
                ('store_email', models.EmailField(default='info@mystore.com', max_length=254)),
                ('phone', models.CharField(default='+252 61 000 0000', max_length=30)),
                ('address', models.CharField(default='Mogadishu, Somalia', max_length=255)),
                ('opening_time', models.TimeField(default='08:00')),
                ('closing_time', models.TimeField(default='20:00')),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('free_shipping_minimum', models.DecimalField(decimal_places=2, default=50, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store Settings',
                'verbose_name_plural': 'Store Settings',
            },
        ),
    ]
