services:
  - type: web
    name: django-ecommerce
    runtime: python
    plan: free

    buildCommand: ./build.sh

    startCommand: gunicorn Ecommerce.wsgi:application

    envVars:
      - key: DATABASE_URL
        sync: false

      - key: SECRET_KEY
        generateValue: true

      - key: DEBUG
        value: "False"

      - key: DJANGO_SUPERUSER_USERNAME
        sync: false

      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false

      - key: DJANGO_SUPERUSER_EMAIL
        sync: false

      - key: CLOUDINARY_CLOUD_NAME
        sync: false

      - key: CLOUDINARY_API_KEY
        sync: false

      - key: CLOUDINARY_API_SECRET
        sync: false